In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv('Purchased_Dataset.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [37]:
x=df[['Age','EstimatedSalary']].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [39]:
y=df['Purchased'].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [41]:
from sklearn.model_selection import train_test_split

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.20,random_state=42)


In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)

In [17]:
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [19]:
y_pred = knn_classifier.predict(x_test)

In [21]:
y_pred

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [25]:
confusion_matrix(y_test, y_pred)

array([[46,  6],
       [ 8, 20]], dtype=int64)

In [27]:
accuracy_score(y_test, y_pred)

0.825

# Cross Validation

In [16]:
import numpy as mean
import numpy as std
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

## KFold Cross-Validation

In [19]:
# prepare the cross-validation procedure
cv = KFold(n_splits=10, random_state=1, shuffle=True)

In [23]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)

In [26]:
#create model
#model = logisticReggression()
# evaluation model
scores = cross_val_score(knn_classifier, x, y, scoring='accuracy', cv=cv)

In [28]:
scores

array([0.725, 0.725, 0.725, 0.825, 0.725, 0.9  , 0.675, 0.875, 0.825,
       0.775])

In [36]:
print(scores.mean())

0.7775000000000001


In [39]:
print(scores.std())

0.07110731326663945


# Stratified KFold

In [44]:
from sklearn.model_selection import StratifiedKFold

In [47]:
# Initialize Stratified K-Fold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [48]:
scores1 = cross_val_score(knn_classifier, x, y, scoring='accuracy', cv=skf)

In [52]:
scores1

array([0.7   , 0.825 , 0.75  , 0.8625, 0.7875])

In [54]:
print(scores1.mean())

0.785


# GridSearchCV

In [45]:
from sklearn.svm import SVC

In [47]:
classifier = SVC()

In [49]:
classifier

SVC()

In [51]:
classifier.fit(x_train, y_train)

SVC()

In [53]:
pred_y = classifier.predict(x_test)

In [59]:
# Applying Grid Search to find the best model and the best performance
from sklearn.model_selection import GridSearchCV

parameters = [{'C': [1,100,1000], 'kernel': ['linear']},
             {'C' : [1,100,1000], 'kernel' : ['rbf'],
             'gamma' : [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,]}]

grid_search = GridSearchCV(estimator = classifier,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 10,
                          n_jobs = -1)


In [ ]:
grid_search = grid_search.fit(x_train,y_train)

In [ ]:
grid_search.best_params_         # Best parameter

In [ ]:
#grid_search.best_params_

accuracy = grid_search.best_score_

accuracy

#### SVC

In [ ]:
cm = confusion_matrix(x_test, pred_y)

### XGBClassifier

In [ ]:
from xgboost import XGBClassifier

In [ ]:
# declare parameters
params = {
            'objective': 'binary:logistc',
            'max-depth': 4,
            'learning_rate': 1.0,
            'n_estimators':100
}

In [ ]:
# instantiate the classifier
xgb_clf = XGBClassifier(**params)

In [ ]:
xgb_clf.fit(x_train, y_train)

In [ ]:
parameters = [{'C': [1,100,1000], 'kernel': ['linear']},
             {'C' : [1,100,1000], 'kernel' : ['rbf'],
             'gamma' : [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,]}]

In [ ]:
grid_search = GridSearchCV(estimator = classfier,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 10,
                          n_jobs = -1)

In [ ]:
grid_search.best_params_

In [ ]:
accuracy = grid_search.best_score_

In [ ]:
accuracy